# Default values for my-rails-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
image:
  repository: my-rails-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 3000
# ingress:
#   enabled: false
#   annotations: {}
#   hosts:
#     - host: my-rails-app.local
#       paths: ["/"]
#   tls: []
