apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-rails-app.fullname" . }}
  labels:
    app: {{ include "my-rails-app.name" . }}
spec:
  selector:
    app: {{ include "my-rails-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  type: {{ .Values.service.type }}
